"use strict";
var color = "\x1b[32m%s\x1b[0m";
console.log(`${color}`, "Number Eight: Write addition, subtraction, multiplication, and division operations that each result in the number 8. Be sure to enclose your operations in print statements to see the results.");
var firstNumber = 5;
var secondNumber = 3;
var thirdNumber = 11;
var fourthNumber = 2;
var fifthNumber = 4;
var seventhNumber = 16;
console.log("+ Plus Operation", firstNumber + secondNumber);
console.log('--------------------------');
console.log("- Subtraction Operation", thirdNumber - secondNumber);
console.log("* Multiplication Operation", fourthNumber * fifthNumber);
console.log("/ Division Operation", seventhNumber / fourthNumber);
